# ============================================================
# Quill Frontend - Dockerfile
# Multi-stage build for a compact Next.js standalone container.
# ============================================================

# ---- Stage 1: Dependencies ----
# Node 20 Alpine keeps the dependency image small.
FROM node:20-alpine AS deps

# libc6-compat helps Alpine run packages that expect glibc compatibility.
# This avoids native dependency surprises during npm install or Next builds.
RUN apk add --no-cache libc6-compat

# /app is the isolated working directory inside the container.
WORKDIR /app

# Copy dependency manifests first so npm ci can be cached between source edits.
COPY package*.json ./

# npm ci installs exact versions from package-lock.json for reproducible builds.
RUN npm ci

# ---- Stage 2: Builder ----
# The builder has source code and dev dependencies needed by next build.
FROM node:20-alpine AS builder

# Keep all frontend build files under /app.
WORKDIR /app

# Reuse dependencies from the deps stage instead of reinstalling them.
COPY --from=deps /app/node_modules ./node_modules

# Copy the frontend source into the builder.
COPY . .

# Ensure public/ exists because this repo currently has no public directory.
# The production stage copies it for Next static assets when present.
RUN mkdir -p public

# Accept the browser-facing backend URL from docker-compose at build time.
# NEXT_PUBLIC variables are inlined into client-side Next.js bundles during build.
ARG NEXT_PUBLIC_API_URL

# Accept the public Google reCAPTCHA site key at build time for browser code.
# This is safe to expose; the private verification secret stays backend-only.
ARG NEXT_PUBLIC_RECAPTCHA_SITE_KEY

# NODE_ENV=production enables Next.js production optimizations.
ENV NODE_ENV=production

# Preserve the API URL for client code compiled by next build.
# Without this, Axios could be bundled with an empty baseURL in Docker.
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL

# Preserve the public reCAPTCHA key for the compiled login/register pages.
ENV NEXT_PUBLIC_RECAPTCHA_SITE_KEY=$NEXT_PUBLIC_RECAPTCHA_SITE_KEY

# Build the standalone Next.js server under .next/standalone.
# next.config.ts enables output: "standalone" for this Docker shape.
RUN npm run build

# ---- Stage 3: Production Runner ----
# The final image contains only the standalone server and static assets.
FROM node:20-alpine AS production

# Keep runtime files under /app.
WORKDIR /app

# Production mode disables development-only behavior in Next.js.
ENV NODE_ENV=production

# Bind to all interfaces so Docker port publishing can reach Next.js.
# Binding only to localhost would make the service reachable only inside the container.
ENV HOSTNAME=0.0.0.0

# Create a non-root user before copying files.
# Running as non-root limits damage if the frontend server is compromised.
RUN addgroup -S quill && adduser -S quill -G quill

# Copy the standalone server with the correct owner for the non-root runtime user.
COPY --from=builder --chown=quill:quill /app/.next/standalone ./

# Copy static assets generated by Next.js.
COPY --from=builder --chown=quill:quill /app/.next/static ./.next/static

# Copy public assets. The builder creates this directory even if the repo has none.
COPY --from=builder --chown=quill:quill /app/public ./public

# Copy the Docker-only HTTPS proxy.
# It wraps the standalone HTTP server with TLS without changing application code.
COPY --chown=quill:quill docker-https-proxy.js ./docker-https-proxy.js

# Create the certificate mount point used by docker-compose.
# The mounted certs are read-only at runtime to protect private keys.
RUN mkdir -p certs

# Switch to the non-root user for runtime.
USER quill

# Document the HTTPS frontend port published by docker-compose.
EXPOSE 3000

# Start the HTTPS proxy, which privately launches the standalone Next.js server.
CMD ["node", "docker-https-proxy.js"]
